# Generated by Django 4.2.1 on 2023-05-26 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
                ('token_id', models.BigIntegerField()),
                ('status', models.CharField(default='Open', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_request',
            },
        ),
        migrations.CreateModel(
            name='BankRequestDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('bank_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bankrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brd_donor_id', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brd_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_request_donor',
            },
        ),
    ]
