# Generated by Django 4.2.1 on 2023-05-26 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_collectblood'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectblood',
            name='bank_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bankrequest'),
        ),
    ]
