# Generated by Django 4.2.1 on 2023-05-24 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
                ('token_id', models.BigIntegerField()),
                ('status', models.CharField(default='Open', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receiver_request',
            },
        ),
        migrations.CreateModel(
            name='RequestDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_donor_id', to=settings.AUTH_USER_MODEL)),
                ('receiver_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.receiverrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_donor',
            },
        ),
        migrations.CreateModel(
            name='RequestBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb_bank_id', to=settings.AUTH_USER_MODEL)),
                ('receiver_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.receiverrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rb_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_bank',
            },
        ),
    ]
