# Generated by Django 4.2.1 on 2023-05-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiverrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
